-- CreateEnum
CREATE TYPE "public"."EventName" AS ENUM ('USER_CREATED', 'PRODUCT_CREATED', 'PRODUCT_UPDATED', 'PRODUCT_DELETED', 'PRODUCT_REFUSED', 'VENDOR_CREATED', 'VENDOR_CONFIG_UPDATED', 'VENDOR_PRODUCTS_UPDATED', 'VENDOR_PRODUCTS_STOCK_UPDATED', 'DISCOUNT_CREATED', 'CUSTOMER_CREATED', 'PRICE_OFFER_SENT', 'PRICE_OFFER_ACCEPTED', 'SEARCH_ALERT_SENT', 'CHAT_STARTED', 'FAVORITE_PRODUCT_CREATED', 'SUPPORT_REQUEST_CREATED', 'ADD_TO_CART', 'REMOVE_FROM_CART', 'BEGIN_CHECKOUT', 'ABANDONED_CHECKOUT', 'ORDER_CREATED', 'ORDER_PAID', 'ORDER_LINE_LABELED', 'ORDER_LINE_SHIPPED', 'ORDER_LINE_RECEIVED', 'ORDER_LINE_REFUNDED', 'ORDER_FULFILLED', 'VENDOR_PAYOUT');

-- CreateEnum
CREATE TYPE "public"."AggregateName" AS ENUM ('USER', 'VENDOR', 'DISCOUNT', 'CUSTOMER', 'ORDER');

-- AlterTable
ALTER TABLE "public"."Event" ADD COLUMN     "newAggregateName" "public"."AggregateName" NOT NULL DEFAULT 'USER',
ADD COLUMN     "newName" "public"."EventName" NOT NULL DEFAULT 'USER_CREATED';
