/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v1/auth/shopify": {
    post: operations["ShopifyController_shopifyLogin"];
  };
  "/v1/customers/wallet": {
    get: operations["CustomerController_fetchCustomerWallet"];
  };
  "/v1/customers": {
    put: operations["CustomerController_updateUserInfo"];
  };
  "/v1/negociation-agreement": {
    post: operations["CustomerController_upsertNegociationAgreement"];
    delete: operations["CustomerController_deleteNegociationAgreement"];
  };
  "/v1/customers/vendor-data": {
    get: operations["CustomerController_fetchVendorDataUrl"];
  };
  "/v1/customers/requests": {
    post: operations["CustomerController_createCustomerRequests"];
  };
  "/v1/customers/webhook/signup": {
    post: operations["CustomerWebhooksHasuraController_handleSignupHasuraEvent"];
  };
  "/v1/orders/webhook/paid-event": {
    post: operations["PaidOrderWebhookShopifyController_"];
  };
  "/v1/admin/orders/webhook/paid-event": {
    post: operations["PaidOrderWebhookShopifyController_handlePaidOrderEventAsAdmin"];
  };
  "/v1/orders/webhook/created-event": {
    post: operations["CreatedOrderWebhookShopifyController_handleCreatedOrderEvent"];
  };
  "/v1/orders/webhook/update": {
    post: operations["OrderWebhookSendCloudController_notifyOnParcelUpdate"];
  };
  "/v1/orders/{orderId}": {
    get: operations["OrderController_getOrder"];
  };
  "/v1/orders": {
    post: operations["OrderController_createOrderAsAdmin"];
  };
  "/v1/orders/{orderId}/shipping-label": {
    post: operations["OrderController_getOrCreateShippingLabel"];
  };
  "/v1/admin/fulfillment-orders/{fulfillmentOrderId}/fulfill": {
    post: operations["OrderController_fulFillOrderLineAsAdmin"];
  };
  "/v1/fulfillment-orders/{fulfillmentOrderId}/fulfill": {
    post: operations["OrderController_fulFillOrderLine"];
  };
  "/v1/admin/orders/{orderId}/cancel": {
    post: operations["OrderController_cancelOrderAsAdmin"];
  };
  "/v1/order-lines/{orderLineId}/cancel": {
    post: operations["OrderController_cancelOrder"];
  };
  "/v1/admin/orders/{orderId}/update-status": {
    post: operations["OrderController_updateOrderStatusAsAdmin"];
  };
  "/v1/invoice/preview-payout": {
    get: operations["PayoutController_previewPayout"];
  };
  "/v1/invoice/preview-commission": {
    get: operations["PayoutController_previewCommission"];
  };
  "/v1/invoice/payout": {
    post: operations["PayoutController_executePayout"];
  };
  "/v1/products/create": {
    post: operations["ProductController_createDraftProduct"];
  };
  "/v1/admin/products/create": {
    post: operations["ProductController_createProduct"];
  };
  "/v1/products/{productInternalId}/image": {
    post: operations["ProductController_addProductImage"];
  };
  "/v1/products/{productInternalId}/image/{imageId}": {
    delete: operations["ProductController_deleteProductImage"];
  };
  "/v1/products/by-handle/{productHandle}": {
    get: operations["ProductController_getProductByHandle"];
  };
  "/v1/products/{productInternalId}": {
    get: operations["ProductController_getProduct"];
    patch: operations["ProductController_updateProduct"];
  };
  "/v1/products/{productInternalId}/variants/{productVariantInternalId}": {
    patch: operations["ProductController_updateProductVariant"];
  };
  "/v1/admin/products/{productInternalId}": {
    patch: operations["ProductController_updateProductByAdmin"];
  };
  "/v1/admin/vendors/{vendorId}/products": {
    post: operations["ProductController_triggerVendorProductsUpdateByAdmin"];
  };
  "/v1/admin/products/{productInternalId}/variants/{productVariantInternalId}": {
    patch: operations["ProductController_updateProductVariantByAdmin"];
  };
  "/v1/admin/products/{productInternalId}/moderate": {
    post: operations["ProductController_moderateProduct"];
  };
  "/v1/products/models": {
    post: operations["ProductController_createProductModel"];
  };
  "/v1/commission/create": {
    post: operations["BuyerCommissionController_createAndPublishCommissionProduct"];
  };
  "/v1/commission/compute-line-item": {
    get: operations["BuyerCommissionController_computeLineItemCommission"];
  };
  "/v1/commission/product": {
    get: operations["BuyerCommissionController_computeProductCommission"];
  };
  "/v1/price-offer": {
    post: operations["PriceOfferController_createPublicPriceOffer"];
  };
  "/v1/price-offer/b2b": {
    post: operations["PriceOfferController_createB2BPriceOfferByBuyer"];
  };
  "/v1/price-offer/{priceOfferId}": {
    put: operations["PriceOfferController_updatePriceOffer"];
  };
  "/v1/admin/price-offer/{priceOfferId}": {
    put: operations["PriceOfferController_updatePriceOfferAsAdmin"];
  };
  "/v1/chat/conversation": {
    post: operations["ChatController_getOrCreateConversation"];
  };
  "/v1/chat/message/webhook": {
    post: operations["ChatController_handleNewMessageWebhook"];
  };
  "/v1/buy/payment/checkout": {
    post: operations["PaymentWebController_getOrCreateCheckout"];
  };
  "/v1/buy/payment/eligibility": {
    post: operations["PaymentWebController_checkPaymentEligibility"];
  };
  "/v1/buy/payment/link": {
    post: operations["PaymentWebController_createPaymentLink"];
  };
  "/v1/buy/payment/link/redirect": {
    get: operations["PaymentWebController_redirectToPaymentLink"];
  };
  "/v1/buy/payment/notify": {
    post: operations["PaymentFloaWebhookController_notifyPaymentResult"];
  };
  "/v1/delivery-profile/product-variant/{variantShopifyId}": {
    get: operations["DeliveryProfileController_getProductDeliveryProfile"];
  };
  "/v1/__internal__/heartbeat": {
    get: operations["HealthCheckController_beat"];
  };
  "/v1/shopify/auth": {
    get: operations["ShopifyAuthController_handleAuthentication"];
  };
  "/v1/shopify/auth/callback": {
    get: operations["ShopifyAuthController_handleAuthenticationCallback"];
  };
  "/v1/saved-search": {
    post: operations["SavedSearchController_createSavedSearch"];
  };
  "/v1/saved-search/{savedSearchId}": {
    put: operations["SavedSearchController_updateSavedSearch"];
    delete: operations["SavedSearchController_deleteSavedSearch"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ShopifyLoginResponse: {
      multipassToken: string;
      loginUrl: string;
    };
    UpdateUserInputDto: {
      phoneNumber: string;
    };
    NegociationAgreementInputDto: {
      maxAmountPercent: number;
    };
    NegociationAgreementResponseDto: {
      id: string;
    };
    VendorDataUrlDto: {
      url: string;
    };
    CustomerRequestDto: {
      quantity: number;
      description: string;
      budgetMinInCents?: number;
      budgetMaxInCents?: number;
      neededAtDate: string;
    };
    CreateCustomerRequestsDto: {
      requests: components["schemas"]["CustomerRequestDto"][];
    };
    ShippingAddressDTO: {
      address1: string;
      address2?: string;
      company?: string;
      phone: string;
      firstName: string;
      lastName: string;
      zip: string;
      city: string;
      country: string;
    };
    CreateOrderInputDTO: {
      salesChannelName: string;
      customerId: string;
      shippingAddress: components["schemas"]["ShippingAddressDTO"];
      lineItems: string[];
      priceOfferIds: string[];
    };
    OrderLineFulfillmentDTO: Record<string, never>;
    OrderStatusUpdateDTO: {
      /** @example 2023-01-14 16:54:08 */
      updatedAt: string;
      /** @enum {string} */
      status: "CREATED" | "PAID" | "SHIPPED" | "DELIVERED" | "PAID_OUT" | "CANCELED" | "RETURNED" | "LABELED";
    };
    PreviewCommissionOutputDTO: {
      vendorCommission: number;
      vendorShipping: number;
      buyerCommission: number;
    };
    PayoutInputQuery: {
      /** @description The Shopify id of the order line */
      orderLineShopifyId: string;
      /** @description A comment to store a reason for a price change for example */
      comment?: string;
      /** @description An amount to replace the calculated one */
      amountInCents?: number;
      /** @description A comment to store a reason for a price change for example */
      force?: boolean;
    };
    BundlePriceDTO: Record<string, never>;
    DraftProductInputDto: {
      bundlePrices: components["schemas"]["BundlePriceDTO"][];
    };
    CreatedProductResponseDTO: {
      internalId: string;
    };
    AddProductImageDTO: {
      attachment: string;
      position?: number;
      filename?: string;
    };
    AddProductImageResponseDTO: {
      src: string;
      id: string;
    };
    VariantDTO: {
      internalId: string;
      price: string;
      compare_at_price?: string;
      condition: string;
    };
    SimpleImageDTO: {
      src: string;
      shopifyId: number;
    };
    ProductAdminDTO: {
      status: string;
      vendor: string;
      tags: string[];
      variants: components["schemas"]["VariantDTO"][];
      body_html: string;
      product_type: string;
      images: components["schemas"]["SimpleImageDTO"][];
    };
    ProductUpdateInputDto: {
      /** @enum {string} */
      status?: "ARCHIVED" | "DRAFT" | "ACTIVE";
      bodyHtml?: string;
      title?: string;
      tags?: string[];
      product_type?: string;
      handDeliveryPostalCode?: string;
      metafields?: unknown[];
    };
    AmountDTO: {
      /**
       * @description Value of the amount in the chosen currency
       * @example 124999
       */
      amountInCents: number;
      /**
       * @description The chosen currency
       * @default EUR
       */
      currency?: string;
    };
    ProductVariantUpdateInputDto: {
      quantity?: number;
      price?: components["schemas"]["AmountDTO"];
      compareAtPrice?: components["schemas"]["AmountDTO"];
      condition?: string;
    };
    UUID: Record<string, never>;
    ProductAdminUpdateInputDto: {
      /** @enum {string} */
      status?: "ARCHIVED" | "DRAFT" | "ACTIVE";
      bodyHtml?: string;
      title?: string;
      tags?: string[];
      product_type?: string;
      handDeliveryPostalCode?: string;
      metafields?: unknown[];
      /** @enum {string} */
      manualNotation?: "A" | "B" | "C";
      vendorId?: components["schemas"]["UUID"];
    };
    ModerateProductInputDto: Record<string, never>;
    PimBrand: {
      name: string;
    };
    CreateProductModelDto: {
      name: string;
      manufacturer_suggested_retail_price: number;
      imageUrl: string;
      year: number;
      productType: string;
      brand: components["schemas"]["PimBrand"];
    };
    CommissionInputDto: {
      cartLineIds?: string[];
    };
    Commission: {
      productStoreId: string;
      variantStoreId: string;
      amountInCents: number;
    };
    NewPublicPriceOfferDTO: {
      buyerId: string;
      newPriceInCents: number;
      productId: string;
      productVariantId?: string;
      description?: string;
    };
    PriceOfferDTO: {
      buyerId: string;
      newPriceInCents: number;
      productId: string;
      productVariantId?: string;
      description?: string;
      id: string;
      createdAt: string;
      initiatedBy: string;
      status: string;
      discountCode: string;
    };
    NewB2BPriceOfferDTO: {
      quantity: number;
      buyerUnitPriceInCents: number;
      sellerUnitPriceInCents: number;
      productId: string;
      description: string;
    };
    UpdatePriceOfferDTO: {
      status: string;
    };
    UpdatePriceOfferByAdminDTO: {
      status?: string;
      /** Format: int64 */
      newPriceInCents?: number;
      quantity?: number;
      includedBuyerCommissionPercentage?: number;
      publicNote?: string;
      internalNote?: string;
    };
    ConversationInputDto: Record<string, never>;
    ProductDTO: {
      amount: components["schemas"]["AmountDTO"];
      shipping: string;
      productType: string;
      id: string;
    };
    CartInfoDTO: {
      storeId: string;
      totalAmount: components["schemas"]["AmountDTO"];
      productsCount: number;
      products: components["schemas"]["ProductDTO"][];
    };
    AddressDTO: {
      /**
       * @description Address line
       * @example 1 rue Paul Dijon
       */
      line1: string;
      /**
       * @description Department zipcode
       * @example 38000
       */
      zipCode: string;
      /**
       * @description The city name
       * @example Grenoble
       */
      city: string;
      /**
       * @description The country code
       * @example FR
       */
      countryCode: string;
    };
    CustomerInfoDTO: {
      /** @example Mike */
      firstName: string;
      /** @example Horn */
      lastName: string;
      /** @example tech@barooders.com */
      email: string;
      /**
       * @description Iso formatted birthdate
       * @example 2024-05-27T13:42:41.184Z
       */
      birthDate: string;
      /**
       * @description Department zipcode
       * @example 38000
       */
      birthZipCode: string;
      /**
       * @description Civility (Mr or Ms)
       * @example Mr
       */
      civility: string;
      address: components["schemas"]["AddressDTO"];
      /**
       * @description Phone number with country code
       * @example +33612345678
       */
      phoneNumber: string;
    };
    EligibilityInputDTO: {
      customerInfo: components["schemas"]["CustomerInfoDTO"];
      cartInfo: components["schemas"]["CartInfoDTO"];
      checkoutId: string;
      paymentSolutionCode: string;
    };
    PaymentLinkDTO: {
      /** @description The id of the payment generated at eligibility */
      paymentId: string;
    };
    RefinementDTO: {
      attribute: string;
      type: string;
      label: string;
      value: string;
      operator?: string;
    };
    CreateSavedSearchDTO: {
      name: string;
      type: string;
      resultsUrl: string;
      collectionId?: string;
      query?: string;
      refinements: components["schemas"]["RefinementDTO"][];
      shouldTriggerAlerts: boolean;
    };
    UpdateSavedSearchDTO: {
      collectionId?: string;
      query?: string;
      refinements?: components["schemas"]["RefinementDTO"][];
      shouldTriggerAlerts?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  ShopifyController_shopifyLogin: {
    responses: {
      default: {
        content: {
          "application/json": components["schemas"]["ShopifyLoginResponse"];
        };
      };
    };
  };
  CustomerController_fetchCustomerWallet: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  CustomerController_updateUserInfo: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserInputDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  CustomerController_upsertNegociationAgreement: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["NegociationAgreementInputDto"];
      };
    };
    responses: {
      default: {
        content: {
          "application/json": components["schemas"]["NegociationAgreementResponseDto"];
        };
      };
    };
  };
  CustomerController_deleteNegociationAgreement: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  CustomerController_fetchVendorDataUrl: {
    responses: {
      default: {
        content: {
          "application/json": components["schemas"]["VendorDataUrlDto"];
        };
      };
    };
  };
  CustomerController_createCustomerRequests: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCustomerRequestsDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  CustomerWebhooksHasuraController_handleSignupHasuraEvent: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  PaidOrderWebhookShopifyController_: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  PaidOrderWebhookShopifyController_handlePaidOrderEventAsAdmin: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  CreatedOrderWebhookShopifyController_handleCreatedOrderEvent: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  OrderWebhookSendCloudController_notifyOnParcelUpdate: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  OrderController_getOrder: {
    parameters: {
      path: {
        orderId: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  OrderController_createOrderAsAdmin: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateOrderInputDTO"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  OrderController_getOrCreateShippingLabel: {
    parameters: {
      path: {
        orderId: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  OrderController_fulFillOrderLineAsAdmin: {
    parameters: {
      path: {
        fulfillmentOrderId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrderLineFulfillmentDTO"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  OrderController_fulFillOrderLine: {
    parameters: {
      path: {
        fulfillmentOrderId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrderLineFulfillmentDTO"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  OrderController_cancelOrderAsAdmin: {
    parameters: {
      path: {
        orderId: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  OrderController_cancelOrder: {
    parameters: {
      path: {
        orderLineId: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  OrderController_updateOrderStatusAsAdmin: {
    parameters: {
      path: {
        orderId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrderStatusUpdateDTO"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  PayoutController_previewPayout: {
    parameters: {
      query: {
        /** @description The id of the order */
        orderId: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PayoutController_previewCommission: {
    parameters: {
      query: {
        /** @description The internal id of the product */
        productInternalId: string;
      };
    };
    responses: {
      default: {
        content: {
          "application/json": components["schemas"]["PreviewCommissionOutputDTO"];
        };
      };
    };
  };
  PayoutController_executePayout: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PayoutInputQuery"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  ProductController_createDraftProduct: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["DraftProductInputDto"];
      };
    };
    responses: {
      default: {
        content: {
          "application/json": components["schemas"]["CreatedProductResponseDTO"];
        };
      };
    };
  };
  ProductController_createProduct: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["DraftProductInputDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  ProductController_addProductImage: {
    parameters: {
      path: {
        productInternalId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddProductImageDTO"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["AddProductImageResponseDTO"];
        };
      };
    };
  };
  ProductController_deleteProductImage: {
    parameters: {
      path: {
        productInternalId: string;
        imageId: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ProductController_getProductByHandle: {
    parameters: {
      path: {
        productHandle: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ProductController_getProduct: {
    parameters: {
      path: {
        productInternalId: string;
      };
    };
    responses: {
      default: {
        content: {
          "application/json": components["schemas"]["ProductAdminDTO"];
        };
      };
    };
  };
  ProductController_updateProduct: {
    parameters: {
      path: {
        productInternalId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductUpdateInputDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ProductController_updateProductVariant: {
    parameters: {
      path: {
        productInternalId: string;
        productVariantInternalId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductVariantUpdateInputDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ProductController_updateProductByAdmin: {
    parameters: {
      path: {
        productInternalId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductAdminUpdateInputDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ProductController_triggerVendorProductsUpdateByAdmin: {
    parameters: {
      path: {
        vendorId: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  ProductController_updateProductVariantByAdmin: {
    parameters: {
      path: {
        productInternalId: string;
        productVariantInternalId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductVariantUpdateInputDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ProductController_moderateProduct: {
    parameters: {
      path: {
        productInternalId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ModerateProductInputDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  ProductController_createProductModel: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateProductModelDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  BuyerCommissionController_createAndPublishCommissionProduct: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CommissionInputDto"];
      };
    };
    responses: {
      default: {
        content: {
          "application/json": components["schemas"]["Commission"];
        };
      };
    };
  };
  BuyerCommissionController_computeLineItemCommission: {
    parameters: {
      query: {
        /**
         * @description The price amount (Decimal)
         * @example 29.99
         */
        amount: number;
        /** @description The product vendor. */
        vendor: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  BuyerCommissionController_computeProductCommission: {
    parameters: {
      query: {
        /**
         * @description The handle of a product
         * @example vtt-enduro
         */
        productHandle: string;
        /**
         * @description The id of a product
         * @example 73829019283
         */
        productInternalId: string;
        /** @description The shopify id of a variant. */
        variantShopifyId: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PriceOfferController_createPublicPriceOffer: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewPublicPriceOfferDTO"];
      };
    };
    responses: {
      default: {
        content: {
          "application/json": components["schemas"]["PriceOfferDTO"];
        };
      };
    };
  };
  PriceOfferController_createB2BPriceOfferByBuyer: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewB2BPriceOfferDTO"];
      };
    };
    responses: {
      default: {
        content: {
          "application/json": components["schemas"]["PriceOfferDTO"];
        };
      };
    };
  };
  PriceOfferController_updatePriceOffer: {
    parameters: {
      path: {
        priceOfferId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdatePriceOfferDTO"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PriceOfferController_updatePriceOfferAsAdmin: {
    parameters: {
      path: {
        priceOfferId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdatePriceOfferByAdminDTO"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ChatController_getOrCreateConversation: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConversationInputDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  ChatController_handleNewMessageWebhook: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  PaymentWebController_getOrCreateCheckout: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CartInfoDTO"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  PaymentWebController_checkPaymentEligibility: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["EligibilityInputDTO"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  PaymentWebController_createPaymentLink: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PaymentLinkDTO"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  PaymentWebController_redirectToPaymentLink: {
    parameters: {
      query: {
        /** @description The id of the payment generated at eligibility */
        paymentId: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PaymentFloaWebhookController_notifyPaymentResult: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  DeliveryProfileController_getProductDeliveryProfile: {
    parameters: {
      path: {
        variantShopifyId: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  HealthCheckController_beat: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  ShopifyAuthController_handleAuthentication: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  ShopifyAuthController_handleAuthenticationCallback: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  SavedSearchController_createSavedSearch: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSavedSearchDTO"];
      };
    };
    responses: {
      default: {
        content: {
          "application/json": string;
        };
      };
    };
  };
  SavedSearchController_updateSavedSearch: {
    parameters: {
      path: {
        savedSearchId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateSavedSearchDTO"];
      };
    };
    responses: {
      /** @description Saved search updated */
      204: {
        content: never;
      };
    };
  };
  SavedSearchController_deleteSavedSearch: {
    parameters: {
      path: {
        savedSearchId: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
}
