export const MAX_BREADCRUMBS_LENGTH = 10;
export const BIKE_CATEGORY_ID = 192;
export const PIM_PRODUCT_TYPE_CACHE_TTL_IN_MILLISECONDS = 10 * 60 * 1000;
export const PIM_CATEGORY_CACHE_TTL_IN_MILLISECONDS = 10 * 60 * 1000;
export const PIM_BRANDS_CACHE_TTL_IN_MILLISECONDS = 10 * 60 * 1000;
