version: 2

models:
  - name: products_ranking
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: string
        constraints:
          - type: not_null
          - type: primary_key # not enforced  -- will warn & include
      - name: shopifyid
        data_type: int
      - name: traffic30
        data_type: int
      - name: traffic7
        data_type: int
      - name: traffictot
        data_type: int
      - name: nb_fav
        data_type: int