name: Update staging branch for Hasura

on:
  push:
    branches:
      - staging

jobs:
  update-staging-branch:
    name: Update hasura config for staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update staging branch
        run: |
          git checkout staging
          awk '/total_max_connections: 100/ {sub(/100/, "3")} 1' hasura/metadata/databases/databases.yaml > tmpfile && mv tmpfile hasura/metadata/databases/databases.yaml
          git config --global user.email "tech@barooders.com"
          git config --global user.name "Github Actions"
          git add hasura/metadata/databases/databases.yaml
          git diff-index --quiet HEAD || git commit -m "Update pool settings for staging"
          git push origin staging
      - name: Display branch information
        run: git branch -a
      - name: Send slack notification on failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: GitHub Actions
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON_EMOJI: ‼️
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: An error occurred
          SLACK_MESSAGE: Github Action failed to update staging branch