#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

git diff --cached --name-only | grep 'packages/frontend' && yarn workspace frontend lint-staged
git diff --cached --name-only | grep 'packages/backend' && yarn workspace backend lint-staged
git diff --cached --name-only | grep 'packages/shared-types' && yarn workspace shared-types lint-staged
git diff --cached --name-only | grep 'packages/store' && yarn --cwd packages/store lint-staged
git diff --cached --name-only | grep 'package.json' && node ./scripts/ci/enforceFixedNodeDependencies.js


# Transcrypt pre-commit hook: fail if secret file in staging lacks the magic prefix "Salted" in B64
RELATIVE_GIT_DIR=$(git rev-parse --git-dir 2>/dev/null || printf '')
CRYPT_DIR=$(git config transcrypt.crypt-dir 2>/dev/null || printf '%s/crypt' "${RELATIVE_GIT_DIR}")
"${CRYPT_DIR}/transcrypt" pre_commit
