#!/usr/bin/env sh


# Fetch the latest changes from the remote repository
git fetch origin main

# Get the list of modified files between current commit and origin/main
modified_files=$(git diff --name-only origin/main HEAD)

# Check if any modified files are within the specified folder
if echo "$modified_files" | grep -q "packages/dbt"; then
    dbt run --project-dir packages/dbt --profiles-dir packages/dbt/config/local --target staging
fi
