const floaCodeMapping: {
  merchantReturnCodeName: string;
  merchantReturnCodeId: string;
  complementaryCode: string;
  complementaryName: string;
  source: string;
  description: string;
}[] = [
  {
    merchantReturnCodeName: 'Unknown',
    merchantReturnCodeId: '5',
    complementaryCode: '0',
    complementaryName: 'Unknown',
    source: 'valeur par défaut',
    description: 'Unknown failure scenario',
  },
  {
    merchantReturnCodeName: 'Cancelled',
    merchantReturnCodeId: '6',
    complementaryCode: '0',
    complementaryName: 'Unknown',
    source: 'valeur par défaut',
    description: 'Unknown failure scenario',
  },
  {
    merchantReturnCodeName: 'NotProcessed',
    merchantReturnCodeId: '7',
    complementaryCode: '0',
    complementaryName: 'Unknown',
    source: 'valeur par défaut',
    description: 'Unknown failure scenario',
  },
  {
    merchantReturnCodeName: 'RefusedByBank',
    merchantReturnCodeId: '2',
    complementaryCode: '1',
    complementaryName: 'AmountLimitExceeded',
    source: 'Bank',
    description: 'Amount limit exceeded for the payment',
  },
  {
    merchantReturnCodeName: 'RefusedByBank',
    merchantReturnCodeId: '2',
    complementaryCode: '2',
    complementaryName: 'LimitExceeded',
    source: 'Bank',
    description: 'Insufficient funds or credit limit exceeded',
  },
  {
    merchantReturnCodeName: 'Succeeded',
    merchantReturnCodeId: '0',
    complementaryCode: '4',
    complementaryName: 'Authorized',
    source: 'Bank',
    description: 'The payment was successfully authorized',
  },
  {
    merchantReturnCodeName: 'RefusedByBank',
    merchantReturnCodeId: '2',
    complementaryCode: '5',
    complementaryName: 'BankFraudSuspicion',
    source: 'Bank',
    description: 'The payment was denied by bank for fraud suspicion',
  },
  {
    merchantReturnCodeName: 'RefusedByBank',
    merchantReturnCodeId: '2',
    complementaryCode: '6',
    complementaryName: 'CardExpired',
    source: 'Bank',
    description: 'Credit card is expired',
  },
  {
    merchantReturnCodeName: 'RefusedByBank',
    merchantReturnCodeId: '2',
    complementaryCode: '8',
    complementaryName: 'CardholderNotAuthenticated',
    source: 'Bank',
    description: 'Unable to authenticate the card holder',
  },
  {
    merchantReturnCodeName: 'RefusedByBank',
    merchantReturnCodeId: '2',
    complementaryCode: '9',
    complementaryName: 'DateOfValidityExpired',
    source: 'Bank',
    description:
      'The payment session is expired and can no longer be completed',
  },
  {
    merchantReturnCodeName: 'RefusedByBank/Unknown',
    merchantReturnCodeId: '2-mai',
    complementaryCode: '12',
    complementaryName: 'FraudSuspicion',
    source: 'Floa',
    description: 'The payment was denied for fraud suspicion (BIN)',
  },
  {
    merchantReturnCodeName: 'RefusedByBank',
    merchantReturnCodeId: '2',
    complementaryCode: '13',
    complementaryName: 'IllegalTransaction',
    source: 'Bank',
    description: 'Transaction was flagged as illegal by the bank',
  },
  {
    merchantReturnCodeName: 'RefusedByBank',
    merchantReturnCodeId: '2',
    complementaryCode: '14',
    complementaryName: 'InvalidAcceptor',
    source: 'Bank',
    description: 'The card acceptor is invalid',
  },
  {
    merchantReturnCodeName: 'RefusedByBank',
    merchantReturnCodeId: '2',
    complementaryCode: '15',
    complementaryName: 'InvalidAccount',
    source: 'Bank',
    description: 'The bank account is invalid',
  },
  {
    merchantReturnCodeName: 'RefusedByBank',
    merchantReturnCodeId: '2',
    complementaryCode: '16',
    complementaryName: 'InvalidCardIssuer',
    source: 'Bank',
    description: 'The card issuer is invalid',
  },
  {
    merchantReturnCodeName: 'RefusedByBank',
    merchantReturnCodeId: '2',
    complementaryCode: '17',
    complementaryName: 'InvalidTransaction',
    source: 'Bank',
    description: 'The transaction is invalid',
  },
  {
    merchantReturnCodeName: 'RefusedByBank',
    merchantReturnCodeId: '2',
    complementaryCode: '18',
    complementaryName: 'LostCard',
    source: 'Bank',
    description: 'The card was reported as lost by the card holder',
  },
  {
    merchantReturnCodeName: 'RefusedByBank',
    merchantReturnCodeId: '2',
    complementaryCode: '20',
    complementaryName: 'Referred',
    source: 'Bank',
    description:
      'The payment cannot be processed automatically, please contact the issuing bank',
  },
  {
    merchantReturnCodeName: 'RefusedByBank',
    merchantReturnCodeId: '2',
    complementaryCode: '21',
    complementaryName: 'Refused',
    source: 'Bank',
    description: 'The payment was refused by bank',
  },
  {
    merchantReturnCodeName: 'RefusedByBank',
    merchantReturnCodeId: '3',
    complementaryCode: '23',
    complementaryName: 'SecurityBreach',
    source: 'Bank',
    description: 'Payment not processed due to a risk of security breach',
  },
  {
    merchantReturnCodeName: 'RefusedByBank',
    merchantReturnCodeId: '2',
    complementaryCode: '24',
    complementaryName: 'SecurityRulesViolated',
    source: 'Bank',
    description: 'Payment not processed due to a violation of security rules',
  },
  {
    merchantReturnCodeName: 'RefusedByBank',
    merchantReturnCodeId: '2',
    complementaryCode: '26',
    complementaryName: 'StolenCard',
    source: 'Bank',
    description: 'The card was reported as stolen by the card holder',
  },
  {
    merchantReturnCodeName: 'Failed',
    merchantReturnCodeId: '3',
    complementaryCode: '31',
    complementaryName: 'TransactionTimedOut',
    source: 'Bank',
    description: 'Transaction timed out before completion',
  },
  {
    merchantReturnCodeName: 'Refused',
    merchantReturnCodeId: '1',
    complementaryCode: '33',
    complementaryName: 'UnknownCard',
    source: 'Bank',
    description: 'Unable to identify the credit card',
  },
  {
    merchantReturnCodeName: 'RefusedByBank',
    merchantReturnCodeId: '2',
    complementaryCode: '33',
    complementaryName: 'UnknownCard',
    source: 'Bank',
    description: 'Unable to identify the credit card',
  },
  {
    merchantReturnCodeName: 'RefusedByBank',
    merchantReturnCodeId: '2',
    complementaryCode: '36',
    complementaryName: 'RefusedByScoring',
    source: 'Floa',
    description: 'Payment not processed due to low trust score on this card',
  },
  {
    merchantReturnCodeName: 'RefusedByBank',
    merchantReturnCodeId: '2',
    complementaryCode: '38',
    complementaryName: 'RefusedByScoring2',
    source: 'Floa',
    description: 'Payment not processed due to low trust score on this card',
  },
  {
    merchantReturnCodeName: 'Refused',
    merchantReturnCodeId: '1',
    complementaryCode: '47',
    complementaryName: 'RegisterSubscriptionFailed',
    source: 'Bank',
    description: 'Failure encountered during subscription registration',
  },
  {
    merchantReturnCodeName: 'Refused',
    merchantReturnCodeId: '1',
    complementaryCode: '48',
    complementaryName: 'MissingSecurityNumber',
    source: 'Bank',
    description: 'Missing Security Number',
  },
  {
    merchantReturnCodeName: 'RefusedByBank',
    merchantReturnCodeId: '2',
    complementaryCode: '46',
    complementaryName: 'SoftDeclineNoAuthenticationData',
    source: 'Bank',
    description: 'Payment was soft declined by bank',
  },
  {
    merchantReturnCodeName: 'Pending',
    merchantReturnCodeId: '4',
    complementaryCode: '53',
    complementaryName: 'Fallback3DS',
    source: 'Bank',
    description: 'Fallback 3DS',
  },
  {
    merchantReturnCodeName: 'RefusedByBank',
    merchantReturnCodeId: '2',
    complementaryCode: '54',
    complementaryName: 'ThreeDSV2AccountsNotFound',
    source: 'Bank',
    description: 'The merchant is not configured for 3DSv2 payments',
  },
  {
    merchantReturnCodeName: 'RefusedByBank',
    merchantReturnCodeId: '2',
    complementaryCode: '55',
    complementaryName: 'AuthenticationFailed',
    source: 'Bank',
    description: 'Failure encountered during 3D-Secure authentication',
  },
  {
    merchantReturnCodeName: 'RefusedByBank',
    merchantReturnCodeId: '2',
    complementaryCode: '56',
    complementaryName: 'ContextDefinitivelyRefused',
    source: 'Bank',
    description: 'This payment request is denied by bank permanently',
  },
  {
    merchantReturnCodeName: 'RefusedByBank',
    merchantReturnCodeId: '2',
    complementaryCode: '57',
    complementaryName: 'CardDefinitivelyRefused',
    source: 'Bank',
    description: 'This card is denied by bank permanently',
  },
];

export default floaCodeMapping;
