name: Static analysis & Tests for backend

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - packages/backend/**
      - packages/shared-types/**

env:
  TRANSCRYPT_PASSWORD: ${{ secrets.TRANSCRYPT_PASSWORD }}

jobs:
  static_analysis:
    name: Run static analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Decrypt secrets and generate prisma client
        run: yarn workspace backend run prebuild
      - name: Run ESLint
        run: yarn workspace backend lint
      - name: Check folder structure
        run: yarn workspace backend validate-folder-structure
      - name: Check circular dependencies
        run: yarn workspace backend find-circular-deps
      - name: Run tests
        run: yarn workspace backend test
      - name: Build TS app
        run: yarn workspace backend build
